### ISSUE TITLE
avahi linux not working

### ISSUE THREAD

**Issue by RandLoki** [ketetefid/StorijOS#10]
I followed the quick start guide successfully installed image on 16gb microsd card for raspi 3. I started and enabled avahi on ubuntu 17.10 but every time I go to http://siaberryos.local/ on chrome it says : This site can’t be reached
siaberryos.local’s server IP address could not be found.
Try:

Checking the connection
Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED

It is plugged into ethernet to my router directly. Ive never used avahi and cant find anything on the internet at all after scouring. Any suggestion would be helpfull and hopefully help the next man. Has anyone else got it to work from linux/chrome?

**Comment by RandLoki** [comment]
it was a bad install, I re flashed the image and was good to go. Not sure what caused it.

**Comment by ketetefid** [comment]
There is a problem on your side as the Avahi on Siaberry runs just fine.
How come it does not get an IP? Please come to discord so we can solve your problem more efficiently.
