### ISSUE TITLE
Can't Reach SiaberryOS Web-UI

### ISSUE THREAD

**Issue by Eddiv** [ketetefid/StorijOS#11]
I Have trying using http://siaberryos.local and using the ip address and nothing i get the error:
Took too long to respond

**Comment by pigd0g** [comment]
My network has a 192.168.1.X subnet.  I had to manually configure the /etc/conf.d/net file.  I wanted it to use the IP 192.168.1.11 as it defaults to 192.168.1.100 which I had another device running on.  Had to shut the other device down then go into the WebUI and change the LANIP in there.  Now its working.

**Comment by Eddiv** [comment]
Im not running any other devices that have the ip 192.168.1.100, and i cant go to the WebUI   i get the error:
Took too long to respond or could not find ip address

**Comment by pigd0g** [comment]
Try the following config in /etc/conf.d/net

Replacing the IP 192.168.1.1 with the IP of your router 

config_eth0="192.168.1.100 netmask 255.255.255.0"
routes_eth0="default via 192.168.1.1"
dns_servers_eth0="192.168.1.1"

**Comment by ketetefid** [comment]
What version are you using Eddiv? Try 1.2.3 on siaberry.com. This issue has already been fixed.
