### ISSUE TITLE
typo: 

### ISSUE THREAD

**Issue by Skeyelab** [ketetefid/StorijOS#2]
<img width="897" alt="image 2017-10-28 at 1 33 19 pm" src="https://user-images.githubusercontent.com/313969/32137413-a9aad77c-bbe4-11e7-8ef1-394739851ef4.png">

**Comment by ketetefid** [comment]
Thank you for reporting this mistake. It was fixed.

You might update the UI using "update-webui" right now, or wait until Tuesday when it is done automatically.
