### ISSUE TITLE
Gateway not being set unable to route to internet

### ISSUE THREAD

**Issue by awillems** [ketetefid/StorijOS#4]
Gateway not being set unable to route to internet

I can run 
route add default gw 10.1.1.1 and it works but if the pi restarts i need to go back and add it agian not sure why this is happening

Solved it turns out the DNS was not getting set to anything or was never set so after editing i was able to resolve domain names and after that the downloader for consensus.db started so its all good but in the interface you should add a place to set DNS if the user wants too.
nano /etc/resolv.conf

nameserver	8.8.8.8 
nameserver	8.8.4.4

**Comment by ketetefid** [comment]
The data are read first from a DHCP connection into a static one. Is your router set to broadcast DNS for the clients?

**Comment by trinsic** [comment]
Had the same problem. Had to edit /etc/conf.d/net
routes_eth0 had the DNS servers in it instead of the Routers gateway, changed it to 192.168.1.1 and restarted and it works now.

**Comment by ketetefid** [comment]
Could you please replace /etc/init.d/ipsetter with the file inside this archive? It should solve the problem. 
However, as in my router the DNS and gateway addresses are the same, I myself could not test it. So it needs your kind testing.
After replacing the file and making sure that the permission has the execution bit (you may chmod +x it just to make sure it will be OK), change the internal IP address via the UI and reboot and see if this time it can reach the internet automatically.
Thanks

[ipsetter.gz](https://github.com/ketetefid/SiaBerryOS/files/1545380/ipsetter.gz)

**Comment by trinsic** [comment]
Yep looks like that works.

**Comment by ketetefid** [comment]
I'll release a new version with this modification.
