### ISSUE TITLE
cannot access web ui

### ISSUE THREAD

**Issue by Shane0306** [ketetefid/StorijOS#5]
fresh flash following instructions, yet won't open web ui to login page, tried chrome, safari pc and Mac? over wired connection to same router (tried several) and nothing?

**Comment by ketetefid** [comment]
Have you installed Bonjour Print Services?
Also, don't forget to exactly type http://siaberryos.local (most browsers will initiate a search instead of evaluating the address if you do not type http://)
Can you directly access it by going to the IP it has gotten from the router/modem?
If you have done all of these and still can't access it, chances are that you are connecting through IPv6 which is blocked by default. Can this be the case?

**Comment by Shane0306** [comment]
thanks for the reply, pops right up when I punch in the ip 192.168.0.100

however now, I'm getting an error saying... (under the my sia tab)

Downloading or continuing the download of consensus.db ...
Resolving direct.consensus.siahub.info... failed: Temporary failure in name resolution.

**Comment by ketetefid** [comment]
About reaching the website, http://siaberryos.local should work. Are you on a Mac or Windows?

About the next problem, first through the webshell inside the WebUI login as root. Then do the following:

wget https://github.com/ketetefid/SiaBerryOS/files/1545380/ipsetter.gz
gunzip ipsetter.gz
chmod +x ipsetter
cp ipsetter /etc/init.d/ipsetter

Next, through the WebUI change the Internal IP to "auto" and then reboot. Check if it can reach the internet or not this time.

The issue might be because your router advertises different gateway than the DNS server while in SiaBerry they are assumed to be one. The above is the fix which will be included in version 1.2.1.

**Comment by Shane0306** [comment]
I am on Mac right now but I have a few pc's as well which I have also tried using the URL with no such luck, it now says 403 forbidden you don't have permission to access this server, apache server at siaberryos.local Port 80.


I'm working on the other stuff now, I'll let you know how I go

**Comment by ketetefid** [comment]
403 forbidden is probably because you are connecting through IPv6. So it does find it, but it does not let you see it and that is because IPv6 is blocked. Can you confirm that if you disable IPv6 you can reach the webUI through its name?

**Comment by Shane0306** [comment]
wget: unable to resolve host address ‘github.com’  yeah this is what I got when using the wget command

**Comment by Shane0306** [comment]
yes you were right it was IPv6

**Comment by ketetefid** [comment]
OH..my bad...yea you are not connected at all. 
OK. can you identify gateway address from a locally connected machine?
I mean in windows you can get the default gateway and also the DNS server. Then again through the webshell as root, issue the following:
nano /etc/conf.d/net
Then find the lines about the gateway and DNS and change the IPs if necessary.
After you edited the file, hit Ctrl+x and then press "y" and then:
/etc/init.d/net.eth0 restart
see if you can reach the outside this time.

**Comment by ketetefid** [comment]
Inside the file you will see three lines, the second of which is about the gateway. The last line is about the DNS.

config_eth0="192.168.0.100 netmask 255.255.255.0"
routes_eth0="default via 192.168.0.1"
dns_servers_eth0="192.168.0.1"

**Comment by Shane0306** [comment]
my gateway was NOT 192.168.0.1 it was all kind of messed up, DNS were both correct,I have changed gateway, testing now...

**Comment by Shane0306** [comment]
SiaBerryOS ~ # wget https://github.com/ketetefid/SiaBerryOS/files/1545380/ipsetter.gz
--2017-07-27 17:08:20--  https://github.com/ketetefid/SiaBerryOS/files/1545380/ipsetter.gz      
Resolving github.com... failed: Temporary failure in name resolution.                           
wget: unable to resolve host address ‘github.com’                                               


no good...

I'm getting the same error on the "my Sia" page

**Comment by ketetefid** [comment]
Did you restart net.eth0?
What IP, gateway, DNS addresses does a typical local client get? Can you extract the number from a locally connected machine?

**Comment by Shane0306** [comment]
yes I did, I'll try again...

on my laptop I've got...

IP 192.168.0.68
SNM: 225.225.225.0
Router: 192.168.0.1

DNS 61.9.134.49
61.9.133.193

**Comment by Shane0306** [comment]
SiaBerryOS ~ # /etc/init.d/net.eth0 restart
 * Stopping fail2ban ...                                                                  [ ok ]
 * Stopping apache2 ...                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1
27.0.0.1. Set the 'ServerName' directive globally to suppress this message                [ ok ]
 * Bringing down interface eth0                                                                 
 * Bringing up interface eth0                                                                   
 *   192.168.0.100 ...                                                                    [ ok ]
 *   Adding routes                                                                              
 *     default via 191.168.0.1 ...                                                              
RTNETLINK answers: Network is unreachable                                                 [ !! ]
 *   Waiting for IPv6 addresses (5 seconds) .                                             [ ok ]
SiaBerryOS ~ #  * Starting fail2ban ...                                                         
 * Starting apache2 ...                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1
27.0.0.1. Set the 'ServerName' directive globally to suppress this message                      
2017-07-27 17:15:26,824 fail2ban.server         [3253]: INFO    Starting Fail2ban v0.9.7        
2017-07-27 17:15:26,825 fail2ban.server         [3253]: INFO    Starting in daemon mode   [ ok ]

**Comment by ketetefid** [comment]
Try this:
Login as root through the Webshell and:
cp /etc/conf.d/net  /etc/conf.d/net_backup
nano  /etc/conf.d/net

And then inside the file only put the following:

config_eth0="dhcp"

Delet the other lines. 
Then restart net.eth0 and see if it gets connected or not.

**Comment by Shane0306** [comment]
SiaBerryOS ~ # /etc/init.d/net.eth0 restart
 * Stopping fail2ban ...                                                                        
 * start-stop-daemon: 1 process refused to stop                                                 
 * Failed to stop fail2ban                                                                [ !! ]
 * ERROR: fail2ban failed to stop                                                               
 * Stopping apache2 ...                                                                         
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1
27.0.0.1. Set the 'ServerName' directive globally to suppress this message                [ ok ]
 * ERROR: cannot stop net.eth0 as fail2ban is still up                                          
SiaBerryOS ~ #  * Starting apache2 ...                                                          
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1
27.0.0.1. Set the 'ServerName' directive globally to suppress this message                [ ok ]

**Comment by ketetefid** [comment]
Reboot your Pi.

**Comment by Shane0306** [comment]
it worked!.

anything else we should do?

**Comment by ketetefid** [comment]
OK....At this point:
First, do the ipsetter update. 
Then, issue the following command:
ifconfig | grep inet
See what IP it has gotten. -> You can choose your IP out of this something like xx.xxx.xxx.100

Then:
/bin/ip route
see what it says about the default route -> This would be the gateway

Then:
cat /etc/resolv.conf

See what it says about the nameserver -> This would be the DNS.

Using the three pieces of info, you need to edit the original /etc/conf.d/net and put correct values into that. first, make a backup again:
cp /etc/conf.d/net /etc/conf.d/net_dhcp

Then:
cp /etc/conf.d/net_backup /etc/conf.d/net

And:
nano  /etc/conf.d/net
change the IPs using the numbers you have gotten, including IP, route, and DNS.

Restart net.eth0 and it should be fine.

**Comment by ketetefid** [comment]
After you updated the ipsetter, you might change internal IP through the WebUI first to "auto" and reboot to check if it can set the IP well or not. If that did not work, manually edit the file according to the above.

**Comment by Shane0306** [comment]
Hey Kete,

I was having some issues installing on the USB, I tried and tried but it always came back to "Preparing the USB flash drive" , I have since replaced the USB to a high quality 32gb drive, left it to install again... this time I have had SOME luck...


under the My Sia tab

send and receive coins have popped up but it still says preparing USB Flash Drive under the General Information section (there is no wallet initialization)

**Comment by ketetefid** [comment]
When you setup Sia, only one drive through the usb should be attached. A 16GB or 32GB USB3 is fine. 
If you attach more than one, you will be stuck on that stage.

It must go forward like what you see in the howto. After preparing the USB flash drive, then it will download the consensus and do the other stages. Until this part is completed, you will not be able to initialize a wallet.

**Comment by Shane0306** [comment]
I have only one attached which is the new 32GB drive

It went through the entire install process already but now its saying preparing USB flash drive again under the general section.

Should i just leave it? It has been online for around 36hrs.

**Comment by ketetefid** [comment]
No, in that stage it just formats and prepares the drive so it must not take that long. Is your Pi powered well? I guess whenever the drive is accessed it gets disconnected because of lack of enough power, hence you are stuck on the first stage.

**Comment by ketetefid** [comment]
Try another USB flash, and/or change the adapter if it is rated <2.5Amp.

**Comment by Shane0306** [comment]
I brought an expensive 2.5a adapter, do you think i need more? Its not even getting hot either..

The only thing is i kept an eye on it while it was going through the processes i.e preparing usb, downloading consensus, ect.  

Then after all thats done the send and recieve page pops up.

But then goes back to the “preparing Usb” under the general tab!

Im not giving up on this thing, i want it to work haha!

**Comment by Shane0306** [comment]
Alright ill try the process again and see where i end up, ill keep you posted

**Comment by ketetefid** [comment]
Did it completely download the consensus? And then you see are back to the first stage?Did it complete verifying the blockchain?

**Comment by Shane0306** [comment]
Yeah, i think so because it went to constructing sia in the flash drive and then verifying the blockchain, i left it for about 20-24hrs now i have just checked it and i am back to preparing usb, but its odd because the send/recieve page is there now, it never used to be.

**Comment by ketetefid** [comment]
Try a reboot.

**Comment by ketetefid** [comment]
Also the latest Firefox plays havoc with the UI. Are you, by chance, using this browser? If so, try Chrome instead.

**Comment by ketetefid** [comment]
I am closing this issue. If anything else arose, please open a related bug report.
