### ISSUE TITLE
Time to Verify Blockchain??

### ISSUE THREAD

**Issue by wisco24** [ketetefid/StorijOS#6]
How long does it normally take?   Mine has been running for over 35 hours and still not complete.   Is this normal?

**Comment by ketetefid** [comment]
It all depends on the the speed of USB stick you have used. Is it USB3? Do not use a USB2 one as you will have to wait for more than 2 weeks. You did not encounter any error messages? It still says the verification message? If so, it is fine and you should just wait. Finally, if you thought it might be stuck, issue a reboot.
