### ISSUE TITLE
Can’t Reconnect After Session Expires

### ISSUE THREAD

**Issue by alecrubin** [ketetefid/StorijOS#7]
Getting a weird issue. When I first plug into my raspberry pi I can log in successfully. But, if my session times out, and I have to log back in, the browser says the host is unreachable.

**Comment by alecrubin** [comment]
A temporary fix to this problem is to just reload the page after session expiration, and then log back in.

**Comment by ketetefid** [comment]
Are you still getting the issue? I cannot reproduce this and I have not encountered it in my many logins either.

**Comment by ketetefid** [comment]
Please reopen if it still exists.
